### ISSUE TITLE
Cannot set a tag value for a device when it was deleted once

### ISSUE THREAD

**Issue by bogdanalov** [balena-io/balena-sdk-python#107]
Hello. I am having problems with the Python-SDK. Let me first explain what am I doing right now. I am creating a backup file every day of all variables and tags for device. I am currently working on a backup processor script which  is taking the values and restoring the devices variables and tags. I found an interesting thing while testing the script. When I deleted a tag and after that I tried to set it back on - it is returning "OK" as it exists and it was updated but it doesn't exist and it isn't populated at all. I think, you are caching things up on your end and you are returning this for a faster response. The devices are raspberry pi 3, if that matter.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dl0j)

**Comment by bogdanalov** [comment]
Guys, I found even bigger problem.. When you try to set one tag for a device - it not only updates the given device, it also updates all devices that have the same TAG KEY which is a serious bug.. This is valid for the API in overall, as it is doing the same thing.. I first experienced few months ago with the node.js SDK but didn't know that this was the problem, now I am sure as I tested with a test tag for 2 devices and their both values were updated, although, I used it correctly.

**Comment by nghiant2710** [comment]
@bogdanalov thanks a lot for the report, I'm looking into the issue now and will let you know when it's resolved.

**Comment by bogdanalov** [comment]
@nghiant2710 Thanks. Tell me if you need some more information.

**Comment by nghiant2710** [comment]
@bogdanalov, this is just Python SDK issue and we just released v5.1.0 that has the fix for the issue.
