### ISSUE TITLE
Build issues on Debian stretch and gcc, cffi dependence.

### ISSUE THREAD

**Issue by CarlosLabrado** [balena-io/balena-sdk-python#108]
Hi I am having some issues trying to build the package, specifically in the cffi dependence.

Error:

 arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-haFsHd/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.5m -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.5/c/_cffi_backend.o
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_j379qbe/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-cqnd3icb-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-_j379qbe/cffi/

Docker file.

`# Base image
FROM resin/armv7hf-debian:stretch

# Install required Linux packages
RUN apt-cache policy
RUN apt-get update && apt-get install -yq \
 curl \
 gcc \
 git \
 iputils-ping \
 libboost-all-dev \
 libcurl4-openssl-dev \
 libssl-dev \

 python3 \
 python3-dev \
 python3-pip \
 python3-setuptools \
 modemmanager \
 valgrind && \
 apt-get clean && rm -rf /var/lib/apt/lists/*

# Install required Python packages
RUN pip3 install -U --no-binary :all: \
 git+https://github.com/resin-io/resin-sdk-python.git

# Set the working directory
WORKDIR /usr/src/app

# Copy everything into the container
COPY . ./

COPY env_vars.yaml /data/env_vars.yaml

ENV DBUS_SYSTEM_BUS_ADDRESS unix:path=/host/run/dbus/system_bus_socket

# Start application
CMD ["bash", "start.sh"]`

**Comment by nghiant2710** [comment]
@CarlosLabrado, you just need to install `libffi-dev` and it will install properly

**Comment by CarlosLabrado** [comment]
Thanks, that did it.
