### ISSUE TITLE
Integrate API Keys with SDK

### ISSUE THREAD

**Issue by jviotti** [balena-io/balena-sdk-python#11]
See https://github.com/resin-io/resin-sdk/issues/143 for more explanation.

**Comment by shaunmulligan** [comment]
I see this issue is resolved on the NodeJS sdk, what is the status for the python SDK?

**Comment by nghiant2710** [comment]
@shaunmulligan, forgot to update. This feature is implemented on https://github.com/resin-io/resin-sdk-python/pull/12

**Comment by nghiant2710** [comment]
Fixed on https://github.com/resin-io/resin-sdk-python/pull/12
