### ISSUE TITLE
Application and device functions should support both id/uuid and name

### ISSUE THREAD

**Issue by nghiant2710** [balena-io/balena-sdk-python#111]

**Comment by phil-d-wilson** [comment]
Customer caught out by this here:

https://jel.ly.fish/view-user-created-view-b321e5b8-6703-49ef-abfb-260570f18f6f-forum/support-thread-discourse-210255

@nghiant2710 @vipulgupta2048

**Comment by nghiant2710** [comment]
@phil-d-wilson, it's already in my plan but I don't have a date for it yet since this needs a lot of time to implement for all application/device methods.

I will update the ticket when it's ready.

**Comment by otaviojacobi** [comment]
Hello, this feature has been implemented as part of #326 and more details can be found in https://blog.balena.io/balena-python-sdk-v13/ and https://docs.balena.io/reference/sdk/python-sdk/ Most models (device, application, releases etc) can now be queried by ID, UUID (long and short) and slug/name/commit when appropriate, matching the behavior on the node-sdk one.
