### ISSUE TITLE
How to use the SDK via WSGI

### ISSUE THREAD

**Issue by daghemo** [balena-io/balena-sdk-python#124]
I used the Pythonic resin-sdk before from the command line.
Now I'm trying to move some of my code into a WSGI application, but I get:

`OSError: [Errno 13] Permission denied: '/usr/share/httpd/.balena'`

Is there a way to not use such a directory? Maybe using the RESIN_API_KEY?

**Comment by otaviojacobi** [comment]
With https://github.com/balena-io/balena-sdk-python/pull/342 users can use a in-memory settings storage which allows to run without any file system attatched, if you want to use the file system storage and want a different path you can just use the data_directory in the initialization
