### ISSUE TITLE
Unable to set device to specific release, "Release is not valid for this device"

### ISSUE THREAD

**Issue by ejohnso49** [balena-io/balena-sdk-python#125]
I currently cannot set a device to a specific release with the Python SDK. I tried using both the release hash and the release ID.

**Release Hash:** `RequestError: b'"Release is not valid for this device"'`
**Release ID:** `ReleaseNotFound: <RELEASE_ID>`

I am able to set the release using the shell scripts [here](https://github.com/balena-io-projects/staged-releases), using the same UUID I attempted with the Python SDK.

I'm not sure what changed recently because I was able to use the Python SDK to do this same operation earlier this week.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ipej)

**Comment by ejohnso49** [comment]
I think this problem is because the device I am attempting to set a release for is offline. The only successful operations I have had with calling `device.set_to_release` for an offline device are with it's current release hash or with setting the device to track the application again. Is this the expected behavior? I think that's okay, but the error message is misleading.

**Comment by xginn8** [comment]
If two releases exist with the same commit hash and one has failed, this error is thrown (the SDK does not filter based on the status of the release when getting a release by hash).

**Comment by ejohnso49** [comment]
I don't think this is limited to the case of multiple releases with same commit hash. I'm hitting this error right now with the SDK, but using the staged-releases repo worked to pin a device to it's current release.

**Comment by nghiant2710** [comment]
hi @ejohnso49, can you please elaborate on the issue you have?

With current implementation, the SDK doesn't filter out unsuccessful releases or releases from another app (there can be a super small chance that 2 apps have same commit hash) and we will address them in the referenced PR. If you think these are not your case then please let us know so we can fix this properly.

Thank you :)

**Comment by ejohnso49** [comment]
I'm sorry, I think I misunderstood the previous comments and now I understand what is causing the failure. I have two applications and occasionally I will push to my test application the same commit which will be pushed to another application after I test it. This case applies to the commit that I ran into the issue with yesterday. Thanks for the explanation. I think #140 will fix my problems.
