### ISSUE TITLE
Clarify dependencies for SDK installation

### ISSUE THREAD

**Issue by tdicola** [balena-io/balena-sdk-python#127]
I noticed the docs don't mention a few implicit dependencies that were necessary to get the SDK to install on a basic debian container.  In particular some of the SDK dependencies needed a few libssl and other dev headers available to build their extensions, here's a bit from a Dockerfile that I found works great:
```
FROM balenalib/armv7hf-debian:stretch

# Install python 3 and balena SDK dependencies.
RUN install_packages build-essential python3 python3-pip python3-setuptools \
    python3-dev python3-wheel libffi-dev libssl-dev

# Install balena python SDK in python 3.
RUN pip3 install balena-sdk
```
It could be handy to update the docs here and show or mention a similar install: https://www.balena.io/docs/reference/sdk/python-sdk/

**Comment by zrzka** [comment]
Another user [hits this](https://forums.balena.io/t/trouble-installing-balena-python-sdk-on-python-container-image/6186).
