### ISSUE TITLE
Creating environment variables fails with 'Database Error'

### ISSUE THREAD

**Issue by eugenefab** [balena-io/balena-sdk-python#145]
In the past week, attempts to call DeviceEnvVariable.create() have failed with `Database Error` which appears to come back as a 404 from your API. I've modified the source here:
https://github.com/balena-io/balena-sdk-python/blob/master/balena/models/environment_variables.py#L100
by changing the parameter name to just 'name' from 'env_var_name' and the call started working correctly again. Since the above code has been the same for many versions of this SDK, I suspect something is going on the API server side of things?

This is a blocker for our code base. Thoughts on how to proceed would be appreciated!

**Comment by Page-** [comment]
Hey, `name` is indeed what should be sent to the api's v4/v5 whereas `env_var_name` is for older versions so it sounds like your fix would be correct, although I believe the api may have been unintentionally accepting `env_var_name` in addition to `name` previously - I'll take a look at that and see if I can restore that behaviour for v4/v5

**Comment by eugenefab** [comment]
So how should I go about resolving this in the interim? Would you be able to restore the previous behavior in short order, or should I create a PR for the fix?

**Comment by Page-** [comment]
If you can create a PR that'd be great, if not then @nghiant2710 should be able to (my python is very limited so I'd be worried I'd break more than I'd fix PRing it myself).  For the API side it will probably take a couple of workdays between writing/testing/deploying the fix

**Comment by eugenefab** [comment]
Do you have specific guidelines for PRs and contribution?

**Comment by eugenefab** [comment]
I've created the PR here: https://github.com/balena-io/balena-sdk-python/pull/146
