### ISSUE TITLE
How does subscribe work?

### ISSUE THREAD

**Issue by xandfury** [balena-io/balena-sdk-python#148]
Hi!
Trying to get my logs stream from a running balena device. This is what I have tried so far:
```python
>>> from balena import Balena
>>> balena = Balena()
>>> balena.auth.login_with_token('<token>')
>>> balena.models.config.get_device_types()  # works :-)
>>> _logs = balena.logs.Logs()
>>> _logs.subscribe('<device_uuid>', test)
>>>
```

This is my test function:
```
>>> def test(data):
...     print(data)
...     return
... 
>>> 
```

I imagined that I would get the some data from the device after this. What might be the correct way to approach this? :slightly_smiling_face:

**Comment by xandfury** [comment]
Never mind. I thought creating a thread for every subscription can be a bit expensive. Got things working with `requests`
```python
r = requests.get('https://api.balena-cloud.com/device/v2/<uuid>/logs?stream=1', data=None, headers=headers, stream=True)

>>> for line in r.iter_lines():
...     if line: # filter out keep-alive new lines
...         print(json.loads(line))
```

**Comment by nghiant2710** [comment]
@xandfury, your approach is correct however you won't see anything immediately since your callback is called when a full line received. So you might need to wait a bit until you see the first line printed (it depends on what is returned by the API)

You should also add an error callback to see if anything goes wrong.

**Comment by xandfury** [comment]
Yeah. Thanks :+1: Have you given a thought about using `async` instead of `twisted`? Maybe be more pythonic :wink:

**Comment by nghiant2710** [comment]
@xandfury indeed but we need a solution that works for both Python 2 and 3 so `twisted` was selected.
