### ISSUE TITLE
supervisor api key is wrong

### ISSUE THREAD

**Issue by fcmichalefty** [balena-io/balena-sdk-python#158]
Version 8.1.0
In line 37 in /usr/local/lib/python3.6/site-packages/balena/models/supervisor.py
SUPERVISOR_API_KEY = os.environ.get('BALENA_SUPERVISOR_ADDRESS') or os.environ.get('RESIN_SUPERVISOR_API_KEY')

must be

SUPERVISOR_API_KEY = os.environ.get('BALENA_SUPERVISOR_API_KEY') or os.environ.get('RESIN_SUPERVISOR_API_KEY')

**Comment by nghiant2710** [comment]
@fcmichalefty thank you for your report, this issue was fixed in v8.1.1 which is just released today
