### ISSUE TITLE
Bug in the `application.get_all()` & `device.get_all()` methods

### ISSUE THREAD

**Issue by richbayliss** [balena-io/balena-sdk-python#163]
User reports that the `application.get_all()` method returns an empty array for them. @thgreasi  was able to replicate the issue by creating a simple balena app with the python sdk & authenticated using both the injected `BALENA_API_KEY` as well as a new user API key.

In both cases `application.get_all()` returned an empty array, `application.get(<app_name>)` was only able to retrieve the current app & `device.get_all()` was only returning the current device.

**Comment by xginn8** [comment]
@thgreasi using a device api key in the node.js SDK exhibits the same behavior (access to only the device who's key it is, and no application access [empty array]). is it possible that this behavior is actually correct?

**Comment by thgreasi** [comment]
@xginn8 the results are correct given the device api key, the fact that the user can't set a different api key to be used by the sdk when the `BALENA_API_KEY` or `RESIN_API_KEY` env var exists is the actual UX issue.
I would expect that calling `login_with_token()` should allow me to specify in a different api key that I want the SDK to be using from that point and after. That's what the user (& myself) was trying to do.

**Comment by nghiant2710** [comment]
Fixed in https://github.com/balena-io/balena-sdk-python/pull/169
