### ISSUE TITLE
root logger configuration in supervisor.py breaks logging settings for parent modules

### ISSUE THREAD

**Issue by kwmlodozeniec** [balena-io/balena-sdk-python#167]
The way logging is configured in supervisor.py breaks logging settings when balena-sdk is imported into another module. Please consult this page on how logging should be configured in a library

https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library

https://github.com/balena-io/balena-sdk-python/blob/682a14f0db75fed8f5ca869821ffa45aeacd1b39/balena/models/supervisor.py#L11

**Comment by nghiant2710** [comment]
hey @kwmlodozeniec, this has been fixed in the latest release (v9.0.0). Can you please update the sdk and try again?

**Comment by kwmlodozeniec** [comment]
Hey @nghiant2710 just tried latest SDK and issue is no longer there. Thanks for a quick resolution!
