### ISSUE TITLE
Balena Default Config Location Set Configurable

### ISSUE THREAD

**Issue by kornpow** [balena-io/balena-sdk-python#175]
`Settings file not found or not in proper format. Rewriting default settings to: /home/user/.balena/balena.cfg`

I was running into an issue with using this library on AWS Lambda. The system that runs the package is ephemeral, and the only filesystem directory that is writable is /tmp. I made a branch where I changed the default location for the config file to be /tmp instead of ~. It might make sense to be able to define where this config file is created, or not create it at all. My branch:  sako0938/balena-sdk-python.

**Comment by otaviojacobi** [comment]
Hello it is possible to use a different path by setting data_directory on balena sdk intialization. Also, with #342 it is now possible to use the sdk totally in memory (nothing persisted on the file system) by setting `"data_directory": False` on the sdk initialization.
