### ISSUE TITLE
HOME_DIRECTORY is read-only on AWS Lambdas

### ISSUE THREAD

**Issue by tekollt** [balena-io/balena-sdk-python#194]
When using the balena-sdk-python with AWS Lambda functions, '~' is read only.

There should be a check to make sure that the default HOME_DIRECTORY is writable or not, and if not it should fall back to use '/tmp' as this would solve the problem with running the sdk on Lambda`s. This would also solve #175  @nghiant2710

**Comment by FRVisser** [comment]
Yes, ran in the same issue!

**Comment by ollytheninja** [comment]
This should be fixed by #200 - you will need to upgrade to v11.0.0.
Set `BALENA_SETTINGS_HOME_DIRECTORY` to the directory you want it in, I just set mine to `/tmp`
Figured this out from the comments in #200 but would be great to get it into the docs
