### ISSUE TITLE
Looking up a device by short UUID doesn't work

### ISSUE THREAD

**Issue by nbertram** [balena-io/balena-sdk-python#197]
The Python SDK does an "equals" filter for UUID here:

https://github.com/balena-io/balena-sdk-python/blob/ecbf08f9f6760b55c002b2aec42abc0dd89f1fce/balena/models/device.py#L88

Whereas the JS SDK does a startsWith filter in the equivalent place:

https://github.com/balena-io/balena-sdk/blob/2689ff8ea064ba1a2ef170e70258f0c1d76308d1/lib/models/device.ts#L514

When a short UUID is provided, the startsWith filter needs to be used instead of eq, as the short UUID is the first 7 chars of the full UUID.

The [existing handling](https://github.com/balena-io/balena-sdk-python/blob/b68c9c3e90e308641c2da8a6ad7b069c1f097fcb/balena/models/device.py#L95) to throw AmbiguousDevice if two returned devices share a short UUID remains sufficient, though confusing in context of the strict equals as it should be impossible to have > 1 devices with the same full UUID...

**Comment by otaviojacobi** [comment]
Hello I know it has been a long while but this feature was released as part of balena-python-sdk v13: https://blog.balena.io/balena-python-sdk-v13/ #326
