### ISSUE TITLE
Docs-Connection failure error for Python SDK

### ISSUE THREAD

**Issue by ghost** [balena-io/balena-sdk-python#201]
SDK docs not available on the Balena.io reference web page due to a "connection failure". Node.js docs are fine. 

https://www.balena.io/docs/reference/sdk/python-sdk/

![image](https://user-images.githubusercontent.com/52132193/104376551-66dc7c80-54e2-11eb-939b-a4f70c73b968.png)

**Comment by nghiant2710** [comment]
This is fixed now
