### ISSUE TITLE
Release get_latest_by_application returns all releases regardless of final status

### ISSUE THREAD

**Issue by pipex** [balena-io/balena-sdk-python#220]
This goes along with adding support for draft/final releases for python SDK.

Here is the line in the code that makes the request 
https://github.com/balena-io/balena-sdk-python/blob/master/balena/models/release.py#L133

**Comment by otaviojacobi** [comment]
Hello, this should have been fixed as part of #326 where we now explicitely search for all the top 1 application where status is `success` which is exact the same behavior as the node-sdk does, for reference:

node query: https://github.com/balena-io/balena-sdk/blob/87b846fae0c54a2cbcdd7750483c082e7608a9f1/src/models/release.ts#L333-L350

python query: https://github.com/balena-io/balena-sdk-python/blob/master/balena/models/release.py#L174-L195
