### ISSUE TITLE
pyOpenSSL outdated

### ISSUE THREAD

**Issue by alejoxbg** [balena-io/balena-sdk-python#228]
Some authentication libraries require an updated pyOpenSSL, but when trying to update, I get this error from Balena-SDK that it uses version 18.0.0.0 and that it is incompatible with version 22.0.0.

![image](https://user-images.githubusercontent.com/58972175/152046152-e8176655-8829-4fd2-be29-62dbdf7a44a3.png)

**Comment by nghiant2710** [comment]
Hey @alejoxbg, just want to let you know that we released v11.1.0 that fix the issues with dependencies so please upgrade your balena python sdk to that version and try again.
