### ISSUE TITLE
documented examples are incorrect, numerous places

### ISSUE THREAD

**Issue by m10d** [balena-io/balena-sdk-python#243]
balena-sdk `11.3.1`.  Viewing docs on `master` (I looked for a "v11" or similar branch but do not see one, and no notes of version differences are listed in the markdown doc)

for example, trying to add an environment variable. the example says:
```python
>>> balena.models.environment_variables.device.create('8deb12a58e3b6d3920db1c2b6303d1ff32f23d5ab99781ce1dde6876e8d143','test_env4', 'testing1')
{'name': u'test_env4', u'__metadata': {u'type': u'', u'uri': u'/balena/device_environment_variable(42166)'}, u'value': u'testing1', u'device': {u'__deferred': {u'uri': u'/balena/device(115792)'}, u'__id': 115792}, u'id': 42166}
```

actual output running this command (with or without a valid UUID from my account)
```python
AttributeError: module 'balena.models.environment_variables' has no attribute 'device'
```
I can see that there is a class `DeviceEnvVariable` - however semantically the available functionality doesn't add up:

- the `create` method takes `key:val` params, 
- but the method is `instance` not `static/class` bound ... not clear semantically how you "create(key,value)" an environment variable, on an _instance_ of the environment variable class.

**Comment by nghiant2710** [comment]
Hi @m10d, thank you for the report and sorry for the confusion in our docs, on the top of the docs we have a getting started section as below:
```
>>> from balena import Balena
>>> balena = Balena()
>>> credentials = {'username':<your email>, 'password':<your password>}
>>> balena.auth.login(**credentials)
...
```

So it implies that all the examples in the docs use a SDK instance not static/class methods. We will add a notice to make this clear to you and other users. Thank you for your contribution.

**Comment by m10d** [comment]
> use a SDK instance not static/class methods

I agree with this specific statement, but respectfully

- `SDK instance` would seem to mean _just_ the `Balena` object, not "all nested object types"
- regardless, the examples given in each class are _wrong_, referencing static calls
- and further, while `Balena` sdk instance clearly needs to keep state (ie implies an Instance), - the individual calls I'm referring to do NOT have any state needed

specifically:

1. `Balena` is least-surprise to be an instance, because you *must* be keeping state -  otherwise you'd have to expect to provide creds to _every_ api call, which would be atypical - and impossible since those calls have not have any `cred`-related args.
1. but `DeviceEnvVariable()` is *not* least surprise to be an instance; it has no state to encapsulate.  I would argue for your team this is a (albeit, not unheard of) misapplication of `OO` principals.  Python allows a cleaner, easier to discover, way just using `classmethod`s

all that notwithstanding - I didn't submit this issue to critique your design ;) - just ask that the examples be updated to be *correct*.  Especially given it's not exactly a Least Surprise discovery to find the correct calls, this would significantly lower the barrier to adopting the API.

Thanks!

**Comment by bernhardkaindl** [comment]
@m10d do you have a working example to create and env variable?

**Comment by nghiant2710** [comment]
@bernhardkaindl, here is an example of creating an device environment variable
```
>>> from balena import Balena
>>> balena = Balena()
>>> credentials = {'username':<your email>, 'password':<your password>}
>>> balena.auth.login(**credentials)
>>> balena.models.environment_variables.device.create('<DEVICE_UUID>','<ENV_VAR_NAME>', '<ENV_VAR_VALUE>')
```

To create other types of environment variable, please follow the examples in our docs.

**Comment by otaviojacobi** [comment]
Hello @m10d , I know this has been a while but we moved away from having examples of returned objects directly into the docs but rather into having proper type hints of the returned types for the SDK, you can check those in https://docs.balena.io/reference/sdk/python-sdk/#types I worked on making sure they are up to date with our API version. Please let us know if you still find mismatching arguments. You can also check some more details in https://blog.balena.io/balena-python-sdk-v13/
