### ISSUE TITLE
Upload GPS data to the Balena API via the Python SDK

### ISSUE THREAD

**Issue by mbastida123** [balena-io/balena-sdk-python#245]
Hi, 

I've seen that the Node SDK has an API for uploading GPS data to the Balena Cloud (https://www.balena.io/docs/reference/sdk/node-sdk/#device-setcustomlocation-uuidorid-location-code-promise-code-). I was wondering if there's the same API on the Python SDK

**Comment by nghiant2710** [comment]
Hey @mbastida123, we do have the same API on the Python SDK, please have a look at https://www.balena.io/docs/reference/sdk/python-sdk/#function-set_custom_locationuuid-location.

**Comment by mbastida123** [comment]
> Hey @mbastida123, we do have the same API on the Python SDK, please have a look at https://www.balena.io/docs/reference/sdk/python-sdk/#function-set_custom_locationuuid-location.

Well that's embarassing.

All the time I was ctrl+F for GPS or tracking and it didn't occur to me that it would be listed as location :)

Thank you!!
