### ISSUE TITLE
Implement global settings for Python SDK

### ISSUE THREAD

**Issue by nghiant2710** [balena-io/balena-sdk-python#25]
`Settings` instances among models and classes are not consistent which means current settings is not global. 
We need to reimplement settings to make it global

**Comment by rgiese** [comment]
The current model is effectively passing configuration data from class instance to class instance by throwing it into a single file in the file system. It'd be great to instead be able to instantiate a proper client class and remove the filesystem entirely. The downsides of the current approach are that my Resin creds (token) get dropped into the filesystem whether I want to or not, and the single user-global file means that authenticating as different users at the same time (be it in one or multiple processes) is impossible.

**Comment by otaviojacobi** [comment]
With #342 users can use a in-memory settings storage which allows to run without any file system attatched, this way you can authenticate with different users and also do it with a file system by using different data_directory if needed
