### ISSUE TITLE
Method of requesting Update Supervisor to target Supervisor_Version

### ISSUE THREAD

**Issue by MoodyMusicMan** [balena-io/balena-sdk-python#268]
I have not seen a method of requesting that the supervisor update to a specified supervisor_version with the SDK.

Am I missing it, or does this feature not exist?

**Comment by nghiant2710** [comment]
@MoodyMusicMan, that method is currently not available but will be added very soon. I will let you know when it is released.

**Comment by MoodyMusicMan** [comment]
Thank You! We are working on a few automation methods for updates, and this is a big help.

**Comment by nghiant2710** [comment]
Hey @MoodyMusicMan, we released `v12.1.0` that contains the method to set supervisor version for a device. Please let us know if you have any further questions.
