### ISSUE TITLE
Stop using `startswith` in API request if possible to avoid unnecessarily expensive query for the API 

### ISSUE THREAD

**Issue by nghiant2710** [balena-io/balena-sdk-python#277]
The SDK should do a direct comparison wherever possible.

See: https://balena.zulipchat.com/#narrow/stream/346007-balena-io.2FbalenaCloud/topic/SDK.20uuidOrId

**Comment by otaviojacobi** [comment]
Currently we allow customers to use short UUIDs in most endpoints per #326 and we need to use startswith for these ones. All other cases will try to fetch for the full UUID/ID which is the exact same behavior as the js-sdk one.
