### ISSUE TITLE
How to use Balena SDK with balena staging environment?

### ISSUE THREAD

**Issue by u93** [balena-io/balena-sdk-python#281]
We need to test against Balena Staging environment... In order to deploy our release we use Balena Python SDK. Read an article that mentioned how to do it with the CLI, but could not find anything for the SDK

**Comment by otaviojacobi** [comment]
Hello @u93 sorry for the late response on this. You can achieve what you want by setting the api_endpoints setting like
```python
from balena import Balena

b = Balena()
b.settings.set('api_endpoint', 'https://api.balena-staging.com')
...
```

**Comment by otaviojacobi** [comment]
There are actually more steps to get the sdk api on a working state for this, it was mostly functional for me setting:
```python
from balena import Balena

b = Balena()
b.settings.set('api_endpoint', 'https://api.balena-staging.com')
b.settings.set('pine_endpoint', 'https://api.balena-staging.com/v6/')
b.settings.set('builder_url', 'https://builder.balena-staging.com/')
```

I do understand however that this workflow is complex and we should be able to set the balena/oB backend domain only once.

**Comment by otaviojacobi** [comment]
Hello @u93 with the release of balena-python-sdk v13 #326 settings objects can now be used with the constructor itself, which allows for multiple objects pointing to different instances of the SDK and a much easier configuration to point to staging environment.

If you want to change for the staging environment, you could simply do:
balena = Balena({"balena_host": "balena-staging.com"})

However, this will overwrite your balena-cloud settings (stored api keys etc). So we recommend using
a different data_directory for each balena-sdk instance, e.g:

```python
balena_prod = Balena()
balena_staging = Balena({
    "balena_host": "balena-staging.com",
    "data_directory": "/home/balena-staging-sdk/.balena",
})
