### ISSUE TITLE
Service environment variable name incorrect in Documentation (should be `var` not `env_var`)

### ISSUE THREAD

**Issue by joel35** [balena-io/balena-sdk-python#330]
In the documentation relating to [ServiceEnvVariable](https://github.com/balena-io/balena-sdk-python/blob/master/DOCUMENTATION.md#serviceenvvariable), the variable name provided in the documentation is `env_var`. The provided example is:

```python 
balena.models.service.env_var.get(1234,'test_env4')
```

However, this raises the following exception:
```
AttributeError: 'Service' object has no attribute 'env_var'
```

Looking at the source code, the correct variable name is `var` with an updated version of the example working correctly.

```python 
balena.models.service.var.get(1234,'test_env4')
```
This is the case for all documentation relating to `ServiceEnvVariable` objects.

The documentation should be updated to reflect the correct variable name.

**Comment by otaviojacobi** [comment]
Thanks for raising @joel35 I will fix the docs right away

**Comment by otaviojacobi** [comment]
Hello @joel35 I fixed the docs regarding this and added some more examples on how to set up Balena settings on #331 

The docs website: https://docs.balena.io/reference/sdk/python-sdk/#examples-153 is also updated.
