### ISSUE TITLE
On Python3 the SDK also needs urlparse

### ISSUE THREAD

**Issue by imrehg** [balena-io/balena-sdk-python#35]
While on Python 2 it works fine, the SDK seems to have a missing dependency on Python 3.

```
Python 3.5.2 (default, Jun 28 2016, 08:46:01) 
[GCC 6.1.1 20160602] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import resin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/greg/resin/prog/bluemix-resin-python/venv3/lib/python3.5/site-packages/resin/__init__.py", line 9, in <module>
    from .base_request import BaseRequest
  File "/home/greg/resin/prog/bluemix-resin-python/venv3/lib/python3.5/site-packages/resin/base_request.py", line 7, in <module>
    from urlparse import urljoin
ImportError: No module named 'urlparse'
```

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_12i3)

**Comment by nghiant2710** [comment]
@imrehg, currently our SDK only supports python 2. I will make time for Python 3 version soon :)

**Comment by imrehg** [comment]
@nghiant2710 thanks for the heads up! May we keep this issue open in the meantime as a reminder?

**Comment by craigmulligan** [comment]
Hey @nghiant2710 how much work does this require? I just got a ping via support, we should bring to @lekkas attention if it's worthwhile.

**Comment by craigmulligan** [comment]
This connects to #45
