### ISSUE TITLE
Device `restart_service` fails silently

### ISSUE THREAD

**Issue by pipex** [balena-io/balena-sdk-python#354]
Replication steps

```
>>> from balena import Balena
>>> balena = Balena()
>>> credentials = { 'username':'me@domain.com', 'password': '******' }
>>> balena.auth.login(**credentials)
>>> balena.models.device.restart_service('uuid', 1234)
```

Nothing is returned from the last command, and the service is not restarted on the dashboard.

Tested with the latest balena-sdk version (14.4.0)

**Comment by cywang117** [comment]
Fixed in v14.4.4 with https://github.com/balena-io/balena-sdk-python/pull/359
