### ISSUE TITLE
Docs for device tags are incorrect

### ISSUE THREAD

**Issue by shaunmulligan** [balena-io/balena-sdk-python#366]
In the documentation, the code examples use `balena.models.device.tag.set('890233e65de76d854d627ce9c8a7ffe0', 'testtag','test1')` which fails with:
```
AttributeError: 'Device' object has no attribute 'tag'
```
The model needs to be the plural `tags.set`

We need to update all the examples in https://github.com/balena-io/balena-sdk-python/blob/master/balena/models/device.py where `.tag` is used incorrectly.

**Comment by otaviojacobi** [comment]
fixed by https://github.com/balena-io/balena-sdk-python/pull/367
