### ISSUE TITLE
models.device.pin_to_release not working

### ISSUE THREAD

**Issue by klillywhite** [balena-io/balena-sdk-python#374]
Version of balena-sdk-python: 15.0.2
Version of python: Python 3.12.2

When I run balena.models.device.pin_to_release(device_uuid, int(release_id)) I got back 

```
Request error: "No fields to update" 400
```

Using the api with the same data worked just fine.

```python
import requests
        url = f'https://api.balena-cloud.com/v7/device(uuid=\'{device_uuid}\')'
        headers = {
            'Content-Type': 'application/json',
            'Authorization': f'Bearer {self.auth_token}'
        }
        data = {"is_pinned_on__release": int(release_id)}
        response = requests.patch(url, headers=headers, data=json.dumps(data))
```

**Comment by otaviojacobi** [comment]
Hello @klillywhite thanks for reporting. I could not reproduce, I tried different cases with a device belonging to a different fleet, a device that was moved from other fleet and standard releases of the app, everything worked for me. Do you have more details you could share?

**Comment by otaviojacobi** [comment]
Hello thanks for your reporting. Today one customer was able to find a reproduction of this and we figured it out this was actually coming from a bad cache of the API underlying version on balena.cfg. In fact, this version should not be accounted from the settings cache. We are working on a fix for the next version
