### ISSUE TITLE
SDK docs don't document constructor

### ISSUE THREAD

**Issue by lurch** [balena-io/balena-sdk-python#43]
On https://docs.resin.io/tools/python-sdk/ there's no documentation about what, if any, init-args the `Resin()` constructor takes.

**Comment by otaviojacobi** [comment]
Hello, this has been fixed as per #332 now the constructor settings can be found on the top of the file with the getting started instructions: https://github.com/balena-io/balena-sdk-python/blob/master/DOCUMENTATION.md#balena-python-sdk
