### ISSUE TITLE
Add support for Python3

### ISSUE THREAD

**Issue by nghiant2710** [balena-io/balena-sdk-python#45]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1dph)

**Comment by imrehg** [comment]
@nghiant2710 any update for this?

**Comment by goodes** [comment]
I just hacked a version that uses six and also properly decodes the request response. As there are no unit tests I am unsure how good my fix is. Does anyone want to test this?

It is in the branch 'add-py3-six-support'

https://github.com/goodes/resin-sdk-python/tree/add-py3-six-support

**Comment by lurch** [comment]
Fixed in #55
