### ISSUE TITLE
resin_client.auth.is_logged_in() raises resin.exceptions.Unauthorized if not logged in 

### ISSUE THREAD

**Issue by benoitguigal** [balena-io/balena-sdk-python#46]
Steps to reproduce:
```
resin_client = Resin()
resin_client.auth.is_logged_in()
```
It raises a `Unauthorized` error, I believe it should return `False`in this case

**Comment by cacsar** [comment]
Just hit this as well, and I believe this is contrary to the documentation. Looking at the code I see https://github.com/resin-io/resin-sdk-python/blob/master/resin/auth.py#L142 catches a RequestException but not other sorts, it looks to me like #18 only took care of the positive case not the negative case.

**Comment by nghiant2710** [comment]
@cacsar, https://github.com/resin-io/resin-sdk-python/issues/18 is not relevant here. This issue is due to some updates in the request builder class so it will throw `Unauthorized` before sending a request.
I'm sorry for the inconvenience and will send a PR to fix this shortly.
