### ISSUE TITLE
Support changing device name

### ISSUE THREAD

**Issue by jhermsmeier** [balena-io/balena-sdk-python#49]
Support changing device name as in the node SDK, i.e.:

```js
resin.models.device.rename(process.env.RESIN_DEVICE_UUID, 'some-new-name');
```

**Comment by nghiant2710** [comment]
@jhermsmeier we do have that function: https://docs.resin.io/tools/python-sdk/#function-rename-uuid-new_name-

**Comment by jhermsmeier** [comment]
Oh boy, I don't know how I missed that. Thanks for clarifying!
