### ISSUE TITLE
Exceptions aren't exported

### ISSUE THREAD

**Issue by jhermsmeier** [balena-io/balena-sdk-python#52]
There doesn't seem to be a way to access the SDK's defined exceptions from a dependant

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_48wx)

**Comment by nghiant2710** [comment]
You can import the resin exceptions by doing something like `from resin import exceptions as resin_exceptions`

**Comment by jhermsmeier** [comment]
Thanks, @nghiant2710 – maybe this could be added to the documentation, as there seem to be quite a few people looking for this information (or just wouldn't figure it out, like me)?
