### ISSUE TITLE
Add function to check whether application/device enables support access or not

### ISSUE THREAD

**Issue by nghiant2710** [balena-io/balena-sdk-python#54]

**Comment by lurch** [comment]
@pimterry Maybe this'd be a useful function for https://github.com/resin-io/resin-sdk too?

**Comment by pimterry** [comment]
@lurch Potentially, sure - I've filed an issue at https://github.com/resin-io/resin-sdk/issues/441. I don't think it's super high priority (as far as I'm aware, we don't need it internally, and no external users have asked for it), but it might be nice to have anyway.

**Comment by nghiant2710** [comment]
fixed in https://github.com/resin-io/resin-sdk-python/pull/53
