### ISSUE TITLE
Add support for authenticating with user api keys

### ISSUE THREAD

**Issue by thgreasi** [balena-io/balena-sdk-python#62]
See: https://forums.resin.io/t/server-to-server-authentication/1919/9?u=thgreasi

**Comment by kornpow** [comment]
Also in deep need for this to be fixed. It is already working on the NodeJS version of the SDK.

**Comment by kornpow** [comment]
Just updated my resin-python-sdk to version 4.0.0 since I realized I'd been running on an old one. Indeed this is still an issue, and quite strange as the feature works on NodeJS.
