### ISSUE TITLE
API Endpoints Update

### ISSUE THREAD

**Issue by kornpow** [balena-io/balena-sdk-python#74]
Hello I posted on the gitter chat about an issue where setting a single environment variable causes all environment variables in the project to be changed, making my devices basically unusable. 

Example code:
`
resin = Resin()

key = open("/blah/blah/blah/resin_key",'r')
token = key.readline().rstrip()
print(token)

resin.auth.login_with_token(token)
print("Is Login Successful?: " + str(resin.auth.is_logged_in()) )

import pprint
pp = pprint.PrettyPrinter(indent=4)

env = resin.models.environment_variables.device.get_all('{uuid}')

pp.pprint(env)

resin.models.environment_variables.device.update({var_id},"This should only change one")
`
This is also from Gitter:
Shaun Mulligan
@shaunmulligan
14:02

Okay @sako0938 , I have reproduced this, its a bug in our translation layer. The node.js SDK isn't affected by it because it has been updated to use the latest API version, but the python sdk hasn't been updated yet, so it uses older endpoints that have translation logic behind them to make sure the data maps onto the new model changes we deployed.

I will get the guys to fix this asap

**Comment by nghiant2710** [comment]
@sako0938, this issue was fixed in v4.0.0
