### ISSUE TITLE
Get name (From 4.0.0 Update) is broken

### ISSUE THREAD

**Issue by kornpow** [balena-io/balena-sdk-python#78]
resin.models.device.get_name("#####")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/skorn/Babylon-Web/django/env/lib/python3.6/site-packages/resin/models/device.py", line 202, in get_name
    return self.get(uuid)['device_name']
KeyError: 'device_name'

When you go find the file /resin/models/device.py in the repo it talks about a large breaking change, so it seems something is just a bit off with the 4.0.0 update.

Thanks for the support!

**Comment by nghiant2710** [comment]
@sako0938, can you please check if your config file still points to another api version other than v4? Since we don't update your config file if it does exist and mandatory key are not missing so there can be a chance, it still points to API v3 which doesn't return `device_name`

**Comment by kornpow** [comment]
@nghiant2710 You are right... I found where the file was stored, and moved it to a backup file. The SDK remakes a new config file in the way that it likes

**Comment by Page-** [comment]
@nghiant2710 I think the endpoint version should be decided by the SDK rather than a config file - pointing to a version the SDK doesn't support is always going to have issues
