### ISSUE TITLE
resin-sdk 4.7.0 has requirement pubnub<4.0.0, but you'll have pubnub 4.1.0 which is incompatible.

### ISSUE THREAD

**Issue by drandreaskrueger** [balena-io/balena-sdk-python#95]
is there any good and general way to avoid this version conflict ?

https://github.com/energywebfoundation/bond/issues/6#issuecomment-398098093

at the moment, when not giving any versions, that [list of dependencies](https://gist.github.com/drandreaskrueger/6a6259f9d0856535f1ed1f1585c2bc33) can just not be installed. 

Problematic are `web3 4.3.0` and `resin-sdk 4.7.0`.

Thanks.

**Comment by nghiant2710** [comment]
@drandreaskrueger, we're going to remove pubnub in the next major release very soon so you will no longer have this conflict. So sorry for the inconvenience.

**Comment by nghiant2710** [comment]
@drandreaskrueger we just released a new version and pubnub is now removed so hope that your issue is fixed now.
